import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdtempSync, writeFileSync, readFileSync, existsSync, rmSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'
import { ClaudeMdGenerator } from './claude-md-generator.js'

describe('ClaudeMdGenerator', () => {
  let tmpDir: string
  let generator: ClaudeMdGenerator

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'claude-md-test-'))
    generator = new ClaudeMdGenerator()
  })

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true })
  })

  describe('generate()', () => {
    it('produces a string with the auto-generated header comment', () => {
      const result = generator.generate({
        projectName: 'My Project',
        content: '## Architecture\nNext.js app.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result).toContain('Auto-generated by ContextGit')
      expect(result).toContain('Do not edit manually')
    })

    it('includes the content in the output', () => {
      const result = generator.generate({
        projectName: 'My Project',
        content: '## Architecture\nNext.js app.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result).toContain('## Architecture')
      expect(result).toContain('Next.js app.')
    })

    it('includes the project name', () => {
      const result = generator.generate({
        projectName: 'Loqally',
        content: 'Some content.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result).toContain('Loqally')
    })
  })

  describe('write()', () => {
    it('creates CLAUDE.md when it does not exist', async () => {
      const result = await generator.write(tmpDir, {
        projectName: 'My Project',
        content: '## Architecture\nNext.js.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result.file).toBe('CLAUDE.md')
      expect(result.warning).toBeUndefined()
      expect(existsSync(join(tmpDir, 'CLAUDE.md'))).toBe(true)
    })

    it('overwrites CLAUDE.md if it was auto-generated by ContextGit', async () => {
      const autoGenContent = '<!-- Auto-generated by ContextGit. Do not edit manually -->\nOld content.'
      writeFileSync(join(tmpDir, 'CLAUDE.md'), autoGenContent)

      const result = await generator.write(tmpDir, {
        projectName: 'My Project',
        content: 'New content.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result.file).toBe('CLAUDE.md')
      expect(result.warning).toBeUndefined()
      const written = readFileSync(join(tmpDir, 'CLAUDE.md'), 'utf-8')
      expect(written).toContain('New content.')
      expect(written).not.toContain('Old content.')
    })

    it('wires @-include as first line of CLAUDE.md and preserves original content', async () => {
      writeFileSync(join(tmpDir, 'CLAUDE.md'), '# My manually written CLAUDE.md\nDo not overwrite.')

      const result = await generator.write(tmpDir, {
        projectName: 'My Project',
        content: 'Generated content.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result.file).toBe('CLAUDE.contextgit.md')
      expect(result.warning).toBeDefined()
      expect(result.warning).toContain('wired into CLAUDE.md')
      // @-include wired as first line
      const claudeContent = readFileSync(join(tmpDir, 'CLAUDE.md'), 'utf-8')
      expect(claudeContent.split('\n')[0]).toBe('@CLAUDE.contextgit.md')
      // Original content preserved below
      expect(claudeContent).toContain('Do not overwrite.')
      // Sidecar created
      expect(existsSync(join(tmpDir, 'CLAUDE.contextgit.md'))).toBe(true)
    })

    it('wires @-include exactly once when write() is called twice', async () => {
      writeFileSync(join(tmpDir, 'CLAUDE.md'), '# Manual content')

      await generator.write(tmpDir, { projectName: 'P', content: 'c1', timestamp: new Date() })
      await generator.write(tmpDir, { projectName: 'P', content: 'c2', timestamp: new Date() })

      const content = readFileSync(join(tmpDir, 'CLAUDE.md'), 'utf-8')
      const occurrences = content.split('@CLAUDE.contextgit.md').length - 1
      expect(occurrences).toBe(1)
    })

    it('does not modify CLAUDE.md when @-include is already present', async () => {
      const initial = '@CLAUDE.contextgit.md\n\n# Manual content'
      writeFileSync(join(tmpDir, 'CLAUDE.md'), initial)

      await generator.write(tmpDir, { projectName: 'P', content: 'new content', timestamp: new Date() })

      expect(readFileSync(join(tmpDir, 'CLAUDE.md'), 'utf-8')).toBe(initial)
    })

    it('updates CLAUDE.contextgit.md if it already exists from a previous run', async () => {
      writeFileSync(join(tmpDir, 'CLAUDE.md'), '# Manual CLAUDE.md')
      writeFileSync(join(tmpDir, 'CLAUDE.contextgit.md'), '<!-- Auto-generated by ContextGit. Do not edit manually -->\nOld generated.')

      const result = await generator.write(tmpDir, {
        projectName: 'My Project',
        content: 'Latest generated content.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result.file).toBe('CLAUDE.contextgit.md')
      const written = readFileSync(join(tmpDir, 'CLAUDE.contextgit.md'), 'utf-8')
      expect(written).toContain('Latest generated content.')
    })
  })
})
