import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdtempSync, writeFileSync, readFileSync, existsSync, rmSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'
import { ClaudeMdGenerator } from './claude-md-generator.js'

describe('ClaudeMdGenerator', () => {
  let tmpDir: string
  let generator: ClaudeMdGenerator

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'claude-md-test-'))
    generator = new ClaudeMdGenerator()
  })

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true })
  })

  describe('generate()', () => {
    it('produces a string with the auto-generated header comment', () => {
      const result = generator.generate({
        projectName: 'My Project',
        content: '## Architecture\nNext.js app.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result).toContain('Auto-generated by ContextGit')
      expect(result).toContain('Do not edit manually')
    })

    it('includes the content in the output', () => {
      const result = generator.generate({
        projectName: 'My Project',
        content: '## Architecture\nNext.js app.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result).toContain('## Architecture')
      expect(result).toContain('Next.js app.')
    })

    it('includes the project name', () => {
      const result = generator.generate({
        projectName: 'Loqally',
        content: 'Some content.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result).toContain('Loqally')
    })
  })

  describe('write()', () => {
    it('creates CLAUDE.md when it does not exist', async () => {
      const result = await generator.write(tmpDir, {
        projectName: 'My Project',
        content: '## Architecture\nNext.js.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result.file).toBe('CLAUDE.md')
      expect(result.warning).toBeUndefined()
      expect(existsSync(join(tmpDir, 'CLAUDE.md'))).toBe(true)
    })

    it('overwrites CLAUDE.md if it was auto-generated by ContextGit', async () => {
      const autoGenContent = '<!-- Auto-generated by ContextGit. Do not edit manually -->\nOld content.'
      writeFileSync(join(tmpDir, 'CLAUDE.md'), autoGenContent)

      const result = await generator.write(tmpDir, {
        projectName: 'My Project',
        content: 'New content.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result.file).toBe('CLAUDE.md')
      expect(result.warning).toBeUndefined()
      const written = readFileSync(join(tmpDir, 'CLAUDE.md'), 'utf-8')
      expect(written).toContain('New content.')
      expect(written).not.toContain('Old content.')
    })

    it('writes CLAUDE.contextgit.md when CLAUDE.md exists and was NOT auto-generated', async () => {
      writeFileSync(join(tmpDir, 'CLAUDE.md'), '# My manually written CLAUDE.md\nDo not overwrite.')

      const result = await generator.write(tmpDir, {
        projectName: 'My Project',
        content: 'Generated content.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result.file).toBe('CLAUDE.contextgit.md')
      expect(result.warning).toBeDefined()
      expect(result.warning).toContain('@CLAUDE.contextgit.md')
      // Original CLAUDE.md untouched
      expect(readFileSync(join(tmpDir, 'CLAUDE.md'), 'utf-8')).toContain('Do not overwrite.')
      // New file created
      expect(existsSync(join(tmpDir, 'CLAUDE.contextgit.md'))).toBe(true)
    })

    it('updates CLAUDE.contextgit.md if it already exists from a previous run', async () => {
      writeFileSync(join(tmpDir, 'CLAUDE.md'), '# Manual CLAUDE.md')
      writeFileSync(join(tmpDir, 'CLAUDE.contextgit.md'), '<!-- Auto-generated by ContextGit. Do not edit manually -->\nOld generated.')

      const result = await generator.write(tmpDir, {
        projectName: 'My Project',
        content: 'Latest generated content.',
        timestamp: new Date('2026-04-09T10:00:00Z'),
      })
      expect(result.file).toBe('CLAUDE.contextgit.md')
      const written = readFileSync(join(tmpDir, 'CLAUDE.contextgit.md'), 'utf-8')
      expect(written).toContain('Latest generated content.')
    })
  })
})
