import { readFileSync, writeFileSync, existsSync } from 'fs'
import { join } from 'path'

const AUTO_GEN_MARKER = '<!-- Auto-generated by ContextGit. Do not edit manually'

interface GenerateOptions {
  projectName: string
  content: string
  timestamp: Date
}

interface WriteResult {
  file: 'CLAUDE.md' | 'CLAUDE.contextgit.md'
  warning?: string
}

export class ClaudeMdGenerator {
  generate(opts: GenerateOptions): string {
    const { projectName, content, timestamp } = opts
    return [
      `<!-- Auto-generated by ContextGit. Do not edit manually — changes will be overwritten on next project_memory_save. -->`,
      `<!-- Source of truth: .contextgit/ database. Use ContextGit MCP tools to update. -->`,
      `<!-- Last updated: ${timestamp.toISOString()} -->`,
      ``,
      `# ${projectName}`,
      ``,
      content,
    ].join('\n')
  }

  async write(projectRoot: string, opts: GenerateOptions): Promise<WriteResult> {
    const claudeMdPath = join(projectRoot, 'CLAUDE.md')
    const contextgitMdPath = join(projectRoot, 'CLAUDE.contextgit.md')
    const generated = this.generate(opts)

    // CLAUDE.md does not exist — create it
    if (!existsSync(claudeMdPath)) {
      writeFileSync(claudeMdPath, generated, 'utf-8')
      return { file: 'CLAUDE.md' }
    }

    // CLAUDE.md exists — check if it was auto-generated by ContextGit
    const existing = readFileSync(claudeMdPath, 'utf-8')
    if (existing.startsWith(AUTO_GEN_MARKER)) {
      writeFileSync(claudeMdPath, generated, 'utf-8')
      return { file: 'CLAUDE.md' }
    }

    // CLAUDE.md is manually maintained — write to CLAUDE.contextgit.md instead
    writeFileSync(contextgitMdPath, generated, 'utf-8')

    // Wire the @-include into CLAUDE.md (idempotent)
    const claudeContent = readFileSync(claudeMdPath, 'utf-8')
    const includeLine = '@CLAUDE.contextgit.md'
    if (!claudeContent.split('\n').some(l => l.trim() === includeLine)) {
      writeFileSync(claudeMdPath, `${includeLine}\n\n${claudeContent}`, 'utf-8')
    }

    return {
      file: 'CLAUDE.contextgit.md',
      warning: `Context written to CLAUDE.contextgit.md and wired into CLAUDE.md via @-include.`,
    }
  }
}
